---
# Common tasks that we just need.

- name: Update Apt Cache
  apt: update_cache=yes

- include: apt-packages.yml
- include: editors.yml
- include: etckeeper.yml
- include: motd.yml
- include: ssh.yml
- include: tty.yml
