---

# Configure a development environment on the server

- name: Prevent non-ssl and www.
  template: src=nohttp.j2 dest=/etc/nginx/sites-available/nohttp

- name: Enable preventing ssl
  command: ln -s /etc/nginx/sites-available/nohttp /etc/nginx/sites-enabled/nohttp creates=/etc/nginx/sites-enabled/nohttp

- name: Create backend
  template: src=iamcarrico.backend.j2 dest=/etc/nginx/sites-available/iamcarrico.backend
  notify: restart nginx

- name: Create frontend
  template: src=iamcarrico.j2 dest=/etc/nginx/sites-available/iamcarrico
  notify: restart nginx

- name: Enable the backend
  command: ln -s /etc/nginx/sites-available/iamcarrico.backend /etc/nginx/sites-enabled/iamcarrico.backend creates=/etc/nginx/sites-enabled/iamcarrico.backend
  notify: restart nginx

- name: Enable the frontend
  command: ln -s /etc/nginx/sites-available/iamcarrico /etc/nginx/sites-enabled/iamcarrico creates=/etc/nginx/sites-enabled/iamcarrico
  notify: restart nginx

- name: Create all redirects
  template: src=redirect.j2 dest=/etc/nginx/sites-available/redirect
  notify: restart nginx
  tags:
     - redirect

- name: Enable redirects
  command: ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/redirect creates=/etc/nginx/sites-enabled/redirect
  notify: restart nginx
  tags:
     - redirect
