- name: "Server setup tasks"
  hosts: all
  become: true
  roles:
   - common
   - ANXS.nginx
   - varnish
   - php

- name: Development Server
  hosts: development
  become: true
  roles:
    - development

- name: Configure Sites
  tags: site_config
  hosts: all
  become: true
  roles:
    - certs
    - site_config
