- name: "First time setup tasks"
  hosts: all
  remote_user: root
  vars_prompt:
    - name: "username"
      prompt: "Username to add to the box?"
      default: "ian"
    - name: "github"
      prompt: "GitHub username (to get ssh keys)?"
      default: "iamcarrico"
  roles:
    - setup
